name: My first pipeline

on:
  push: 
    branches:
      - main

jobs: 
  build:
  runs-on: ubuntu-latest
    steps:
      -name: Clone the code
       uses: actions/checkout@v4
      -name: Build image
      run:
        docker build -t ballyc/cicd-portfolio .
      -name: Docker login
      uses: docker/login-action@v3
      with:
        username: ballyc
        password: ${{ secrets.DOCKER_PASSWORD }}
      -name: Push image
      run:
        docker push ballyc/cicd-portfolio
