name: Build and Push to ECR

on:
    push:
        # pull_request:
        #     branches: ['main', 'dev']

        branches: ['main']
permissions:
  id-token: write
  contents: read

jobs:
    build_scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v7
            - name: Trivy Scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'fs'
                severity: 'CRITICAL,HIGH'
                exit-code: '0'
            - name: Build Docker Image
              run: docker build -t 366019841221.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
            - name: Scan Docker Image with Trivy
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'image'
                image-ref: '366019841221.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest'
                severity: 'CRITICAL,HIGH'
                exit-code: '0'
                format: 'table'
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::366019841221:role/GitHubActions-Terraform-Role
                aws-region: us-east-1
              
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2  
            
            - name: Push image to ECR
              run: docker push 366019841221.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest

  